# Generated by Django 4.2.11 on 2024-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], default='NE', max_length=2),
        ),
    ]
